import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const ikntLinks: { title: string; link: string }[] = [
  { title: "Новости", link: "/iknt/news" },
  { title: "Преподаватели", link: "/iknt/teachers" },
];

export default function IKNTLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Navbar links={ikntLinks} />
      <main className="bg-gray-100">{children}</main>
    </>
  );
}
